/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainWindow;

import Adaptive_Huffman_Coding.Adaptive_Huffman;
import arithmetic.arthmitic_encode_decode;
import huffman_coding.Huffman;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import lzw.Lzw;
import runLength.en_de_run_length;
import variableLength.Variables;

/**
 *
 * @author Mustafa
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MultiOperations
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBackground(new java.awt.Color(204, 204, 255));
        text.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        text.setForeground(new java.awt.Color(0, 102, 102));
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 1020, 37));

        jButton1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Run Length");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 30));

        jButton2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Variable Run Length");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 290, 30));

        jButton3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Dictionary [LZW]");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 210, 30));

        jButton4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 153));
        jButton4.setText("Exit");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 80, 30));

        jButton5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Huffman Coding");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 210, 30));

        jButton6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Arthimtic Coding");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 290, 30));

        jButton7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 153));
        jButton7.setText("Adaptive Huffman Coding");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 290, 30));

        jButton8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 153, 153));
        jButton8.setText("Show Algorithm");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 250, 30));

        jButton9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 102));
        jButton9.setText("Show Algorithm");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 170, 30));

        jButton10.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 153, 153));
        jButton10.setText("Show Algorithm");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 250, 30));

        jButton11.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 102));
        jButton11.setText("Show Algorithm");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 170, 30));

        jButton12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 153, 153));
        jButton12.setText("Show Algorithm");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 250, 30));

        jButton13.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 102, 102));
        jButton13.setText("Show Algorithm");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 170, 30));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa\\Documents\\NetBeansProjects\\Multimedia_Project_Fourth_Year\\Images\\prologo.png")); // NOI18N
        jLabel3.setText(" ");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 710, 130));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa\\Documents\\NetBeansProjects\\Multimedia_Project_Fourth_Year\\Images\\cr.png")); // NOI18N
        jLabel4.setText("Developed BY : \n Mustafa Omran Anwer     \n   Basem Hamdy Ahmed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 390, 110));
        jLabel4.getAccessibleContext().setAccessibleName("");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 550, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mustafa\\Documents\\NetBeansProjects\\Multimedia_Project_Fourth_Year\\Images\\bg.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(text.getText().length()==0)
{
    JOptionPane.showMessageDialog(null,"Please Insert String ","Warring No Input was Inserted :(",2);
}     
    
     en_de_run_length nn = new en_de_run_length();
     nn.encodeRunLength(text.getText());
     jTextArea1.setText("Result apeared in MSG Dialog . . . \n");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Variables variables = new Variables();
        
       String res =  variables.encodeText(text.getText());
       //jLabel1.setText("final encode: "+res);
        //JOptionPane.showMessageDialog(null, res);
        variables.decodeText();
        jTextArea1.setText("Result\n"+"Encoding\n"+res+"\nDecoding\n"+variables.getSorting().toString()+"\n"+variables.getCoding().toString());
                    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(text.getText().length()==0)
{
    JOptionPane.showMessageDialog(null,"Please Insert String ","Warring No Input was Inserted :(",2);
}        
        
        Lzw lzw = new Lzw();
        
        lzw.encodeLZW(text.getText());
        lzw.decompress();
        jTextArea1.setText(" S = "+lzw.getS()+"\n Output is : \n"+lzw.getOutput()+"\n Decompress : \n"+lzw.getOutput2());
       // JOptionPane.showMessageDialog(null,"s = "+lzw.getS()+"\n output is : \n"+lzw.getOutput()+"\n Decompress : \n"+lzw.getOutput2());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int mu;
        mu=JOptionPane.showConfirmDialog(null,"Do You Want TO Exit","EXIT Confirm MSG :)",0,3);
    }//GEN-LAST:event_formWindowClosing

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(text.getText().length()==0)
{
    JOptionPane.showMessageDialog(null,"Please Insert String ","Warring No Input was Inserted :(",2);
}        // Shows Huffman Algorithem
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if(text.getText().length()==0)
{
    JOptionPane.showMessageDialog(null,"Please Insert String ","Warring No Input was Inserted :(",2);
}
//        String  ca=JOptionPane.showInputDialog("Please Enter The string to check !");
        arthmitic_encode_decode  x = new arthmitic_encode_decode();
        x.input_caharacters(text.getText());
        if(x.check_for_input_string(text.getText()))
		{
//			System.out.println("ready to input");
                    JOptionPane.showInputDialog("Ready to input : Get_new_low_high_range ");
			x.get_new_low_high_range(text.getText());
		}
		else
		{
                    
			JOptionPane.showInputDialog("Wrong Input Try Again !");
		}
//        jTextArea1.setText("Result apeared in MSG Dialog . . . \n");
        
        
       
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // Shows Huffman Algorthim 
         jTextArea1.setText("1. Initialization: Put all symbols on a list sorted according to their frequency counts.\n" +
"\n" +
"2. Repeat until the list has only one symbol left:\n" +
"\n" +
"(1) From the list pick two symbols with the lowest frequency counts.  "+"\n"+
 "\n"    + "Form a Huffman subtree that has these two symbols as child nodes and create a parent node.\n" +
"\n" +
"(2) Assign the sum of the children’s frequency counts to the parent and insert it into the list such that the order is maintained.\n" +
"\n" +
"(3) Delete the children from the list.\n" +
"\n" +
"3. Assign a codeword for each leaf based on the path from the root.");

    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
         // Shows Adaptive Huffman code Algorthim 
        jTextArea1.setText("ENCODER\n" +
"-------\n" +
"Initial_code(); \n" +
"\n" +
"while not EOF\n" +
" {\n" +
"	get(c); \n" +
"	encode(c); \n" +
"	update_tree(c);\n" +
 "}"+"\n\n"+
                "********************************************"+
"\n\n DECODER\n" +
"-------\n" +
"Initial_code();\n" +
"\n" +
"while not EOF \n" +
"{\n" +
"	decode(c);\n" +
"	output(c);\n" +
"	update_tree(c); \n" +
"}");
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        jTextArea1.setText("Encoder\n\n"+"BEGIN\n" +
"	s = next input character;\n" +
"	while not EOF\n" +
"	{ \n" +
"		c = next input character;\n" +
"\n" +
"		if s + c exists in the dictionary\n" +
"		s = s + c;\n" +
"		else\n" +
"		{ \n" +
"		output the code for s;\n" +
"		add string s + c to the dictionary with a new code;\n" +
"		s = c;\n" +
"		}\n" +
"	}\n" +
"	output the code for s;\n" +
"END\n\n"+"********************************************"+"\n\n\nDecoder\n"+"BEGIN\n" +
"	s = NIL;\n" +
"	while not EOF\n" +
"	{\n" +
"		k = next input code;\n" +
"		entry = dictionary entry for k;\n" +
"		output entry;\n" +
"		if (s != NIL)\n" +
"			add string s + entry[0] to dictionary with a new code;\n" +
"		s = entry;\n" +
"	}\n" +
"END");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // Show Arthimtic Algorthim
        
        jTextArea1.setText("BEGIN\n" +
"code = 0;\n" +
"k = 1;\n" +
"while (value(code) < low)\n" +
"{ \n" +
"	assign 1 to the kth binary fraction bit\n" +
"	if (value(code) > high)\n" +
"	replace the kth bit by 0\n" +
"	k = k + 1;\n" +
"}\n" +
"END"+"\n\n\n"+
    "********************************************"+
  "\n\nDecoder\nBEGIN\n" +
   "get binary code and convert to\n" +
"decimal value = value(code);\n" +
"Do\n" +
"{ \n" +
"	find a symbol s so that\n" +
"		Range_low(s) <= value < Range_high(s);\n" +
"	output s;\n" +
"	low = Rang_low(s);\n" +
"	high = Range_high(s);\n" +
"	range = high - low;\n" +
"	value = [value - low] / range;\n" +
"}\n" +
"Until symbol s is a terminator\n" +
"END");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jTextArea1.setText("1. Sort the symbols according to the frequency count of their occurrences.\n" +
"\n" +
"2. Recursively divide the symbols into two parts,\n\n each with approximately the same number of counts,\n\n until all parts contain only one symbol.");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        jTextArea1.setText("• Memoryless Source: \n\n"+""+"an information source that is independently distributed."+
                "\n"+" Namely, the value of the current symbol does not depend on the values of the previously appeared symbols.\n\n"+
                "• Rationale for RLC:\n\n"+
                ""+"if the information source has the property that symbols tend to form continuous groups, \n then such symbol and the length of the group can be coded.");
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if(text.getText().length()==0)
{
    JOptionPane.showMessageDialog(null,"Please Insert String ","Warring No Input was Inserted :(",2);
}
        Adaptive_Huffman al=new Adaptive_Huffman();
        al.adaptive_huffman(text.getText());
         
       
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if(text.getText().length()==0)
{
    JOptionPane.showMessageDialog(null,"Please Insert String ","Warring No Input was Inserted :(",2);
}
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        
        Huffman hu=new Huffman();
        hu.huffman(text.getText());
        //jTextArea1.setText("Result of Huffman Coding is \n"+hu);
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
